sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t zenharbinger/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zenharbinger/react-test npm test

after_success:
  - docker build -t zenharbinger/multi-client ./client
  - docker build -t zenharbinger/multi-nginx ./nginx
  - docker build -t zenharbinger/multi-server ./server
  - docker build -t zenharbinger/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push zenharbinger/multi-client
  - docker push zenharbinger/multi-nginx
  - docker push zenharbinger/multi-server
  - docker push zenharbinger/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'mluti-docker'
  env: 'Mlutidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-825779265118'
  bucket_path: 'mluti-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
